spring:
  profiles:
    active: db, core, wx
  message:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  debug
    org.springframework:  debug
    org.mybatis:  debug
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  debug